/** biome-ignore-all lint/performance/noImgElement: This is a valid use case */
"use client";

import Image from "next/image";

import { Spinner } from "@/components/ui/spinner";
import { cn } from "@/lib/utils";
import { usePresentationState } from "@/states/presentation-state";
import { ChartRenderer } from "../charts/ChartRenderer";
import { EmbedRenderer } from "../embeds/EmbedRenderer";
import ImagePlaceholder from "../image-placeholder";
import { type RootImageProps } from "../root-image";
import {
  getRootImageObjectStyles,
  getRootImageSizeStyle,
} from "../root-image-layout";

export default function RootImageStatic({
  image,
  layoutType,
  slideId,
}: RootImageProps) {
  const isSideLayout = layoutType === "left" || layoutType === "right";
  const rootImageGeneration = usePresentationState(
    (s) => s.rootImageGeneration,
  );
  const rawComputedGen = slideId ? rootImageGeneration[slideId] : undefined;
  const imageQuery = image.query.trim();
  const computedGen =
    rawComputedGen &&
    (!imageQuery || rawComputedGen.query.trim() === imageQuery)
      ? rawComputedGen
      : undefined;
  const computedImageUrl = computedGen?.url ?? image.url;
  const imageStyles = getRootImageObjectStyles(image);
  const sizeStyle = getRootImageSizeStyle(image, layoutType);
  const isRootImageGenerating =
    image.isQueryStreaming ||
    computedGen?.status === "queued" ||
    computedGen?.status === "generating";
  const shouldShowGenerationPlaceholder =
    isRootImageGenerating &&
    !computedImageUrl &&
    !image.embedType &&
    !image.chartType;

  // Root image is now generated by PresentationGenerationManager

  return (
    <div
      className={cn(
        "relative shrink-0",
        isSideLayout && "min-h-0 self-stretch",
      )}
      style={sizeStyle}
    >
      <div
        className={cn(
          "overflow-hidden border bg-background/80 backdrop-blur-xs",
          isSideLayout ? "absolute inset-0" : "h-full",
        )}
        data-root-image={slideId}
        style={{
          borderRadius: "var(--presentation-border-radius, 0.5rem)",
          boxShadow:
            "var(--presentation-card-shadow, 0 1px 3px rgba(0,0,0,0.12))",
        }}
      >
        {shouldShowGenerationPlaceholder ? (
          <div className="flex h-full flex-col items-center justify-center gap-3 bg-muted/30 p-4 text-center">
            <Spinner className="size-8" />
            <div className="space-y-1">
              <p className="text-sm font-medium text-foreground">
                Generating root image
              </p>
              <p className="text-xs text-muted-foreground">
                This can take a moment.
              </p>
            </div>
          </div>
        ) : image.chartType && image.chartData ? (
          <div className="relative h-full">
            <ChartRenderer
              chartType={image.chartType}
              chartData={image.chartData}
              chartOptions={image.chartOptions}
              className="h-full w-full"
            />
          </div>
        ) : image.embedType && image.url ? (
          <div className="relative h-full">
            <EmbedRenderer
              embedType={image.embedType}
              url={image.url}
              className="h-full w-full"
              style={imageStyles}
            />
          </div>
        ) : (
          <div className="relative h-full">
            {computedImageUrl ? (
              <Image
                unoptimized
                width={400}
                height={300}
                src={computedImageUrl}
                alt={image.query}
                style={imageStyles}
              />
            ) : (
              <ImagePlaceholder
                isStatic={true}
                className="h-full"
                slideId={slideId}
                imageNotFound={computedGen?.status === "error"}
              />
            )}
          </div>
        )}
      </div>
    </div>
  );
}
